FROM node:lts
ARG UID
ARG GID
WORKDIR /home/node
RUN apt update && \
    apt -y install \
    git \
    yarn \
    python3 python3-dev python3-pip \
    gcc g++ \
    curl \
    bash \
    rsync && \
    yarn global add gatsby-cli && \
    gatsby options set package-manager yarn
RUN usermod -u $UID -d /home/node -s /bin/bash node
RUN groupmod -g $GID node
RUN mkdir app
RUN mkdir .ssh
EXPOSE 8000 9000
COPY gats/ca/selfca.crt /usr/share/ca-certificates/
RUN echo "selfca.crt" >> /etc/ca-certificates.conf
RUN update-ca-certificates
USER node
WORKDIR /home/node/app